name: AWS EC2 자동 배포

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USERNAME }}

    steps:
      - uses: actions/checkout@v4.1.2

      - name: Show git status
        run: git status

      - name: Prepare SSH connect
        env:
          private_key: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$private_key" > MongleKeypair.pem
          chmod 400 MongleKeypair.pem
          mkdir ~/.ssh
          ssh-keyscan -t rsa,ecdsa,ed25519 $host > ~/.ssh/known_hosts

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: temurin
          java-package: jdk
          architecture: x64
          cache: gradle

      - name: Build Jar
        run: |
          chmod 755 gradlew
          ./gradlew bootJar

      - name: Upload deployment scripts
        run: |
          sudo chmod 755 scripts/deploy/*
          scp -i MongleKeypair.pem -r scripts/deploy/* "${username}@${host}:deploy"

      - name: Upload sql schema
        run: scp -i MongleKeypair.pem -r schema.sql "${username}@${host}:~"

      - name: Update database
        run: ssh -i MongleKeypair.pem "${username}@${host}" "deploy/load_schema.sh"

      - name: Kill current running Spring process
        run: ssh -i MongleKeypair.pem "${username}@${host}" "deploy/shutdown.sh; deploy/backup.sh"

      - name: Send jar file to EC2
        run: |
          jarPath=$(./gradlew -q jarPath)
          scp -i MongleKeypair.pem $jarPath "${username}@${host}:~/server.jar"

      - name: Startup new uploaded jar
        run: ssh -i MongleKeypair.pem "${username}@${host}" "source ~/.env; deploy/startup.sh"

      - name: Wait 30 seconds for server to startup
        run: sleep 30

      - name: Check and Recover
        run: ssh -i MongleKeypair.pem "${username}@${host}" "source ~/.env; deploy/check_and_recover.sh"
